#!/bin/bash
service_file="/etc/systemd/system/x-ui.service"
is_installed=false

if [ -f "$service_file" ]; then
    is_installed=true
fi

show_menu() {
    if [ "$is_installed" = true ]; then
        clear
        echo "1. 安装"
        echo "2. 修改端口号"
        echo "3. 卸载"
        echo "4. 查看安装信息"
        echo "5. 修改密码"
        echo "6. 恢复配置"
        echo "7. 退出"
    else
        clear
        echo "1. 安装"
        echo "7. 退出"
    fi
    echo "x-ui.service安装状态: $( [ "$is_installed" = true ] && echo "已安装" || echo "未安装" )"
    echo "请选择一个选项:"
}

# 安装服务
install_service() {
    echo "执行安装..."
    bash <(curl -Ls https://raw.githubusercontent.com/samu1oto/hygfront/master/xuiconf) || {
        echo "安装过程中发生错误，返回菜单..."
        return 1
    }
    echo "安装完成。请使用菜单中“查看安装信息”功能获取本次安装的信息"
    sleep 3
}

# 修改端口号
change_port() {
    if [ "$is_installed" = true ]; then
        echo "修改端口号..."
        bash <(curl -Ls https://raw.githubusercontent.com/samu1oto/hygfront/master/cgp) || {
            echo "修改端口号过程中发生错误，返回菜单..."
            return 1
        }
        echo "端口号修改成功。"
        sleep 3
    else
        echo "x-ui.service未安装，无法修改端口号。"
    fi
}

# 修改密码
change_pwd() {
    if [ "$is_installed" = true ]; then
        echo "修改密码..."
        bash <(curl -Ls https://raw.githubusercontent.com/samu1oto/hygfront/master/cgpwd) || {
            echo "发生错误，返回菜单..."
            return 1
        }
        echo "密码修改成功。"
        sleep 3
    else
        echo "x-ui.service未安装，无法修改密码。"
    fi
}

# 卸载服务
uninstall_service() {
    if [ "$is_installed" = true ]; then
        echo "执行卸载..."
        x-ui uninstall || {
            echo "卸载过程中发生错误，返回菜单..."
            return 1
        }
        echo "卸载完成。"
        sleep 3
    else
        echo "x-ui.service未安装，无需卸载。"
    fi
}

# 查看安装信息
view_info() {
    if [ "$is_installed" = true ]; then
        echo "查看安装信息..."
        cat results.log
        echo "按任意键继续..."
        read -n 1 -s -r
    else
        echo "x-ui.service未安装，无法查看安装信息。"
    fi
}

restore_conf() {
    if [ "$is_installed" = true ]; then
        echo "确认要恢复配置？所有信息将按照results.log还原"
        echo "按任意键继续..."
        read -n 1 -s -r
        x-ui stop
        cp /etc/x-ui/x-ui.bak /etc/x-ui/x-ui.db
        x-ui start
        echo "配置恢复完成"
        sleep 3
    else
        echo "x-ui.service未安装，请先安装"
    fi
}

# 主循环
while true; do
    show_menu
    read -p "请输入选项: " option
    case $option in
        1)
            install_service
            ;;
        2)
            change_port
            ;;
        3)
            uninstall_service
            ;;
        4)
            view_info
            ;;
        5)
            change_pwd
            ;;
        6)
            restore_conf
            ;;
        7) 
            echo "退出..."
            exit 0
            ;;
        *)
            echo "无效选项，请重新输入。"
            ;;
    esac
    echo "" # 打印空行
done
